services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  weather-app:
    container_name: weather-app-be
    build: .
    image: weather-app-be:1.0
    ports:
      - "3000:3000"
    depends_on:
      postgres-db:
        condition: service_healthy

volumes:
  database-data:
